server:
  port: 8080

spring:
  application:
    name: portfolio-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  cors:
    allowedOrigins: ["http://localhost:3000"]

